### ISSUE TITLE
Bug: Background Repeat on click of start :(

### ISSUE THREAD

**Issue by ayush78781** [Bauddhik-Geeks/Snake-Game#20]
![bug](https://user-images.githubusercontent.com/76848435/139197986-91c59bbd-e54d-43c9-a610-1f46b8f128d6.PNG)
Background is repeating both vertically and horizontally while clicking on the start. I have added the screenshots here. Have a look @harikanani. Can I work upon it in order to fix it.
![bug2](https://user-images.githubusercontent.com/76848435/139197997-995376f2-1b9a-4ea4-a0ec-82ad33ef46d0.PNG)

**Comment by Nitesh-thapliyal** [comment]
@ayush78781 in my case it is working fine but can you remove the scroll and make a display fix so that the whole board is visible?

**Comment by ayush78781** [comment]
> @ayush78781 in my case it is working fine but can you remove the scroll and make a display fix so that the whole board is visible?

Finished working on it and opened a pull request [21](https://github.com/Bauddhik-Geeks/Snake-Game/pull/21) for the same.
