### ISSUE TITLE
[Feature]Add different types of food for the snake

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Snake-Game#3]

**Comment by OmDharme** [comment]
Can I work on this

**Comment by adityamangal1** [comment]
Sure @OmDharme Go ahead

**Comment by OmDharme** [comment]
I have download pngs for 3 other foods - orange, banana and grapes.
Should I just add them in the assets folder or also make a function to get random food every time the snake eats one.

**Comment by harikanani** [comment]
> I have downloaded pngs for 3 other foods - orange, banana and grapes. Should I just add them in the assets folder or also make a function to get random food every time the snake eats one.

Yes, You should add functionality to get random food every time the snake eats one.
